---
title: "heatmap code"
author: "Nora C. Brown, Benjamin Gordon, Caitlin E. McDonough-Goldstein, Snigdha Misra, Geoffrey D. Findlay, Andrew G. Clark, Mariana F. Wolfner"
output: html_document
---

This is an R markdown document to generate heatmaps from expression data from GSE99574 (RNAseq performed across Drosophila species from dissected tissues--Yang et al., 2018). This code is associated with the manuscript "The seminal odorant binding protein Obp56g is required for mating plug formation and male fertility in Drosophila melanogaster".

```{r}
#load packages from library
library(pheatmap)
library(RColorBrewer)
```

```{r}
#expression data subsetted from averaged log2 normalized matrix containing all species/tissues (output file from exp_evo_code.Rmd called avg.all.csv). species specific paralogs pulled out and indicated in "gene status" column
#inference of species orthology/paralogy from syntenic analysis
seminal_obps = read.csv("sfpobps_nrc.csv")
rownames(seminal_obps) <- seminal_obps[,1]
seminal_obps <- seminal_obps[,-1]
```

```{r}
#orthopara_obps.csv contains paralog/ortholog info for column annotation
male.re.all = subset(seminal_obps, select=c("mel.strain_m_re", "yak_m_re", "ana_m_re", "pse_m_re", "per_m_re", "wil_m_re", "moj_m_re", "vir_m_re"))

col_annot = read.csv("orthopara_obps.csv")
rownames(col_annot) <- col_annot[,1]

cols = colorRampPalette(brewer.pal(9,"Blues"))(100)
pheatmap(
  mat               = t(male.re.all),
  border_color      = NA,
  color             = cols,
  show_colnames     = TRUE,
  show_rownames     = TRUE,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  fontsize_row          = 8,
  fontsize_col = 4.5, 
  annotation_col = col_annot,
  #scale="column",
  filename = "male_re.pdf")
```

```{r}
#repeat for male head tissues
male.hd.all = subset(seminal_obps, select=c("mel.strain_m_hd", "yak_m_hd", "ana_m_hd", "pse_m_hd", "per_m_hd", "wil_m_hd", "moj_m_hd", "vir_m_hd"))

col_annot = read.csv("orthopara_obps.csv")
rownames(col_annot) <- col_annot[,1]

cols = colorRampPalette(brewer.pal(9,"Blues"))(100)
pheatmap(
  mat               = t(male.hd.all),
  border_color      = NA,
  color             = cols,
  show_colnames     = TRUE,
  show_rownames     = TRUE,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  fontsize_row          = 8,
  fontsize_col = 4.5, 
  annotation_col = col_annot,
  #scale="column",
  filename = "male_head.pdf")
```


